Repository hngi/expense-bot, pull requests merged in 2020-06, with the labels that each got.

#3 Add api model samples for twitter
  src/models/tweet.json
Labels: documentation

#5 Add express to create endpoints for mock events
  .env.example
  index.js
  package-lock.json
  package.json
  server.js
  src/bot.js
  src/mock/tweet.json
Labels: enhancement

#7 Update readme with use case and twitter usage
  .github/SUPPORT.md
  README.md
Labels: documentation

#9 Add authentication checks for invalid credentials
  .env.example
  README.md
  src/api/authenticate.js
  src/bot.js
Labels: enhancement

#11 Add tweet search feature
  .env.example
  server.js
  src/api/search.js
  src/bot.js
  src/mock/mock-tweets.json
  src/mock/tweet.json
Labels: enhancement

#13 Implement OAuth1.0a to retrieve Twitter API access tokens for @expenseng
  package.json
  server.js
  src/api/authorize.js
  src/api/callback.js
  src/api/consumer.js
  src/bot.js
  src/public/favicon.ico
  src/public/manifest.json
  src/public/style.css
  src/views/index.html
Labels: enhancement

#15 Fix build failing due to package-lock.json out of sync
  package-lock.json
  package.json
Labels: bug

#21 Add node environment tooling packages
  .eslintrc.js
  package-lock.json
  package.json
  server.js
  src/api/authenticate.js
  src/api/authorize.js
  src/api/callback.js
  src/api/reply.js
  src/api/retweet.js
  src/api/search.js
  src/bot.js
  src/config.js
  src/helpers/isReply.js
  src/rando.js
Labels: enhancement

#18 bot can Like tweets where it is tagged(hashtaged(#) or mentions(@))
  src/api/like.js
  src/views/index.html
Labels: enhancement

#22 Update server.js
  server.js
Labels: enhancement

#25 Getting all mentions on timeline #19
  server.js
  src/api/mentions.js
Labels: enhancement

#27 Fix heroku server crash
  server.js
  src/api/like.js
  src/api/mentions.js
  src/views/index.html
Labels: bug

#30 Add html form tag in homepage for POST endpoints
  src/public/style.css
  src/views/index.html
Labels: enhancement

#32 Autohook
  .env.example
  .github/SUPPORT.md
  README.md
  package-lock.json
  package.json
  server.js
  src/bot.js
  src/config.js
  src/helpers/crc.js
  src/helpers/initializeAutohook.js
Labels: enhancement

#34 Update like.js
  src/api/like.js
Labels: enhancement
